/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _appRouteImport } from './routes/__app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilerIndexRouteImport } from './routes/profiler/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as _appPersonasIndexRouteImport } from './routes/__app/personas/index'
import { Route as _appMeetIndexRouteImport } from './routes/__app/meet/index'
import { Route as _appMeIndexRouteImport } from './routes/__app/me/index'

const _appRoute = _appRouteImport.update({
  id: '/__app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilerIndexRoute = ProfilerIndexRouteImport.update({
  id: '/profiler/',
  path: '/profiler/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const _appPersonasIndexRoute = _appPersonasIndexRouteImport.update({
  id: '/personas/',
  path: '/personas/',
  getParentRoute: () => _appRoute,
} as any)
const _appMeetIndexRoute = _appMeetIndexRouteImport.update({
  id: '/meet/',
  path: '/meet/',
  getParentRoute: () => _appRoute,
} as any)
const _appMeIndexRoute = _appMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => _appRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/chat': typeof ChatIndexRoute
  '/profiler': typeof ProfilerIndexRoute
  '/me': typeof _appMeIndexRoute
  '/meet': typeof _appMeetIndexRoute
  '/personas': typeof _appPersonasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/chat': typeof ChatIndexRoute
  '/profiler': typeof ProfilerIndexRoute
  '/me': typeof _appMeIndexRoute
  '/meet': typeof _appMeetIndexRoute
  '/personas': typeof _appPersonasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__app': typeof _appRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/chat/': typeof ChatIndexRoute
  '/profiler/': typeof ProfilerIndexRoute
  '/__app/me/': typeof _appMeIndexRoute
  '/__app/meet/': typeof _appMeetIndexRoute
  '/__app/personas/': typeof _appPersonasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/signin'
    | '/auth/signup'
    | '/chat'
    | '/profiler'
    | '/me'
    | '/meet'
    | '/personas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signin'
    | '/auth/signup'
    | '/chat'
    | '/profiler'
    | '/me'
    | '/meet'
    | '/personas'
  id:
    | '__root__'
    | '/'
    | '/__app'
    | '/auth/signin'
    | '/auth/signup'
    | '/chat/'
    | '/profiler/'
    | '/__app/me/'
    | '/__app/meet/'
    | '/__app/personas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _appRoute: typeof _appRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ProfilerIndexRoute: typeof ProfilerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__app': {
      id: '/__app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiler/': {
      id: '/profiler/'
      path: '/profiler'
      fullPath: '/profiler'
      preLoaderRoute: typeof ProfilerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__app/personas/': {
      id: '/__app/personas/'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof _appPersonasIndexRouteImport
      parentRoute: typeof _appRoute
    }
    '/__app/meet/': {
      id: '/__app/meet/'
      path: '/meet'
      fullPath: '/meet'
      preLoaderRoute: typeof _appMeetIndexRouteImport
      parentRoute: typeof _appRoute
    }
    '/__app/me/': {
      id: '/__app/me/'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof _appMeIndexRouteImport
      parentRoute: typeof _appRoute
    }
  }
}

interface _appRouteChildren {
  _appMeIndexRoute: typeof _appMeIndexRoute
  _appMeetIndexRoute: typeof _appMeetIndexRoute
  _appPersonasIndexRoute: typeof _appPersonasIndexRoute
}

const _appRouteChildren: _appRouteChildren = {
  _appMeIndexRoute: _appMeIndexRoute,
  _appMeetIndexRoute: _appMeetIndexRoute,
  _appPersonasIndexRoute: _appPersonasIndexRoute,
}

const _appRouteWithChildren = _appRoute._addFileChildren(_appRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _appRoute: _appRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  ChatIndexRoute: ChatIndexRoute,
  ProfilerIndexRoute: ProfilerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
